#!/bin/bash
# =============================================================================
# Citrix Auto-Login v2 — Setup Script
# =============================================================================
# Run this ONCE to install everything the auto-login script needs.
#
# WHAT THIS SCRIPT DOES:
# 1. Checks for Python 3 (does NOT auto-install — your IT may restrict this)
# 2. Installs the Python packages we need (playwright, pyyaml)
# 3. Downloads the Playwright Chromium browser
# 4. Stores your Citrix credentials in macOS Keychain
# 5. Generates your config file (~/.citrix-autologin.yaml)
# 6. Creates a keyboard shortcut via an Automator Quick Action
#
# HOW TO RUN:
#   chmod +x setup.sh
#   ./setup.sh
# =============================================================================

set -e  # Exit immediately if any command fails

echo "========================================="
echo "  Citrix Auto-Login v2 — Setup"
echo "========================================="
echo ""

# ---- Step 1: Python 3 ----
echo "Step 1: Checking for Python 3..."
if ! command -v python3 &> /dev/null; then
    echo ""
    echo "  ERROR: Python 3 not found."
    echo "  Install from https://www.python.org/downloads/ or ask IT to install it."
    exit 1
else
    PYVER=$(python3 --version 2>&1)
    echo "  $PYVER ✓"
fi

# ---- Step 2: Python packages ----
echo ""
echo "Step 2: Installing Python packages..."
if pip3 install --user playwright pyyaml 2>/dev/null; then
    echo "  Python packages installed. ✓"
else
    echo ""
    echo "  pip install failed. If you see 'externally managed environment', try:"
    echo "    pip3 install --break-system-packages playwright pyyaml"
    echo ""
    echo "  Then re-run this setup script."
    exit 1
fi

# ---- Step 3: Playwright Chromium ----
echo ""
echo "Step 3: Downloading Playwright Chromium browser..."
if python3 -m playwright install chromium 2>/dev/null; then
    echo "  Chromium downloaded. ✓"
else
    echo ""
    echo "  Chromium download failed."
    echo "  Check your network connection or proxy settings."
    echo "  You can retry with: python3 -m playwright install chromium"
    exit 1
fi

# ---- Step 4: Store credentials in Keychain ----
echo ""
echo "Step 4: Storing your Citrix credentials in macOS Keychain..."
echo "  (Your password will be stored encrypted, not in plain text)"
echo ""
read -p "  Enter your Citrix username: " citrix_user
read -s -p "  Enter your Citrix password: " citrix_pass
echo ""

# Delete any existing entry (ignore errors if it doesn't exist)
security delete-generic-password -s "citrix-autologin" 2>/dev/null || true

# Add the new entry
security add-generic-password -a "$citrix_user" -s "citrix-autologin" -w "$citrix_pass"
echo "  Credentials stored in Keychain. ✓"

# ---- Step 5: Generate config file ----
echo ""
echo "Step 5: Generating config file..."

CONFIG_FILE="$HOME/.citrix-autologin.yaml"

if [ -f "$CONFIG_FILE" ]; then
    read -p "  Config already exists at $CONFIG_FILE. Overwrite? [y/N] " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "  Keeping existing config. ✓"
        SKIP_CONFIG=true
    fi
fi

if [ -z "$SKIP_CONFIG" ]; then
    read -p "  Enter your Citrix login URL [https://gateway.scmc.org/]: " citrix_url
    citrix_url=${citrix_url:-https://gateway.scmc.org/}

    read -p "  Which apps to launch? (comma-separated) [Epic Production, Aria Home, MIM, RayStation 2024A SP3]: " apps_input
    apps_input=${apps_input:-"Epic Production, Aria Home, MIM, RayStation 2024A SP3"}

    # Convert comma-separated string to YAML list
    cat > "$CONFIG_FILE" << YAMLEOF
# Citrix Auto-Login Configuration
# Generated by setup.sh on $(date +%Y-%m-%d)

citrix_url: "$citrix_url"
push_approval_timeout: 120
app_launch_delay: 3
portal_load_wait: 3
headless: false

apps:
YAMLEOF

    # Parse comma-separated apps into YAML list items
    IFS=',' read -ra APP_ARRAY <<< "$apps_input"
    for app in "${APP_ARRAY[@]}"; do
        # Trim whitespace
        app=$(echo "$app" | xargs)
        echo "  - \"$app\"" >> "$CONFIG_FILE"
    done

    echo "" >> "$CONFIG_FILE"
    echo "# Optional: named profiles for different app sets" >> "$CONFIG_FILE"
    echo "# profiles:" >> "$CONFIG_FILE"
    echo "#   clinic:" >> "$CONFIG_FILE"
    echo "#     apps: [\"Epic Production\", \"Aria Home\"]" >> "$CONFIG_FILE"
    echo "#   planning:" >> "$CONFIG_FILE"
    echo "#     apps: [\"MIM\", \"RayStation 2024A SP3\"]" >> "$CONFIG_FILE"

    echo "  Config saved to $CONFIG_FILE ✓"
fi

# ---- Step 6: Create keyboard shortcut via Automator ----
echo ""
echo "Step 6: Creating keyboard shortcut..."

# Get the directory where this setup script lives
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Create an Automator Quick Action that runs the script silently
# (no Terminal window — notifications provide all user feedback)
WORKFLOW_DIR="$HOME/Library/Services/Citrix Auto-Login.workflow"
CONTENTS_DIR="$WORKFLOW_DIR/Contents"

mkdir -p "$CONTENTS_DIR"

# Info.plist — tells Automator this is a "no input" service
cat > "$CONTENTS_DIR/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>NSServices</key>
    <array>
        <dict>
            <key>NSMenuItem</key>
            <dict>
                <key>default</key>
                <string>Citrix Auto-Login</string>
            </dict>
            <key>NSMessage</key>
            <string>runWorkflowAsService</string>
        </dict>
    </array>
</dict>
</plist>
PLIST

# The workflow document — runs the script silently (no Terminal window)
cat > "$CONTENTS_DIR/document.wflow" << WFLOW
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>AMApplicationBuild</key>
    <string>523</string>
    <key>AMApplicationVersion</key>
    <string>2.10</string>
    <key>AMDocumentVersion</key>
    <string>2</string>
    <key>actions</key>
    <array>
        <dict>
            <key>action</key>
            <dict>
                <key>AMAccepts</key>
                <dict>
                    <key>Container</key>
                    <string>List</string>
                    <key>Optional</key>
                    <true/>
                    <key>Types</key>
                    <array>
                        <string>com.apple.cocoa.string</string>
                    </array>
                </dict>
                <key>AMActionVersion</key>
                <string>2.0.3</string>
                <key>AMApplication</key>
                <array>
                    <string>Automator</string>
                </array>
                <key>AMComment</key>
                <string>Runs the Citrix auto-login Python script silently</string>
                <key>AMProvides</key>
                <dict>
                    <key>Container</key>
                    <string>List</string>
                    <key>Types</key>
                    <array>
                        <string>com.apple.cocoa.string</string>
                    </array>
                </dict>
                <key>ActionBundlePath</key>
                <string>/System/Library/Automator/Run Shell Script.action</string>
                <key>ActionName</key>
                <string>Run Shell Script</string>
                <key>ActionParameters</key>
                <dict>
                    <key>COMMAND_STRING</key>
                    <string>python3 -m citrix_autologin ${SCRIPT_DIR} &gt;/dev/null 2&gt;&amp;1 &amp;</string>
                    <key>CheckedForUserDefaultShell</key>
                    <true/>
                    <key>inputMethod</key>
                    <integer>1</integer>
                    <key>shell</key>
                    <string>/bin/bash</string>
                    <key>source</key>
                    <string></string>
                </dict>
                <key>BundleIdentifier</key>
                <string>com.apple.RunShellScript</string>
                <key>CFBundleVersion</key>
                <string>2.0.3</string>
                <key>CanShowSelectedItemsWhenRun</key>
                <false/>
                <key>CanShowWhenRun</key>
                <true/>
                <key>Category</key>
                <array>
                    <string>AMCategoryUtilities</string>
                </array>
                <key>Class Name</key>
                <string>RunShellScriptAction</string>
                <key>InputUUID</key>
                <string>0</string>
                <key>Keywords</key>
                <array>
                    <string>Shell</string>
                    <string>Script</string>
                </array>
                <key>OutputUUID</key>
                <string>0</string>
                <key>UUID</key>
                <string>0</string>
                <key>UnlocalizedApplications</key>
                <array>
                    <string>Automator</string>
                </array>
            </dict>
        </dict>
    </array>
    <key>connectors</key>
    <dict/>
    <key>workflowMetaData</key>
    <dict>
        <key>serviceInputTypeIdentifier</key>
        <string>com.apple.Automator.nothing</string>
        <key>workflowTypeIdentifier</key>
        <string>com.apple.Automator.servicesMenu</string>
    </dict>
</dict>
</plist>
WFLOW

echo "  Automator Quick Action created. ✓"
echo ""

# ---- Done! ----
echo "========================================="
echo "  SETUP COMPLETE!"
echo "========================================="
echo ""
echo "ONE REMAINING STEP:"
echo ""
echo "  Set up a keyboard shortcut:"
echo "  → System Settings → Keyboard → Keyboard Shortcuts → Services"
echo "  → Find 'Citrix Auto-Login' in the General section"
echo "  → Click 'Add Shortcut' and press your desired key combo"
echo "  → Recommended: Ctrl+Shift+C"
echo ""
echo "To test, run:  python3 -m citrix_autologin"
echo ""
echo "After pressing your shortcut, you'll get macOS notifications:"
echo "  1. 'Check your phone' — approve the Authenticator push"
echo "  2. 'All apps launched!' — your Citrix apps are starting"
